### ISSUE TITLE
Typescript compatibility

### ISSUE THREAD

**Issue by BjoernRave** [snipsnapdev/snipsnap#21]
Currently the snippets only work in `.js` files. It would be nice to have them work in `{.ts|.tsx}` files as well. It would be great if the snippets would be typed as well

**Comment by deadcoder0904** [comment]
Yeah was thinking why this isn't working bcz I was using `.tsx` lol

**Comment by lnikell** [comment]
Hi @BjoernRave and @deadcoder0904! I don't have experience with Typescript, that's why I was not able to clearly tell which snippets could be used in TS without extra modification. 
Basically there are no technical limitations for this, a declaration in which file snippet should work comes from `scope` key inside each snippet:
```
  "classnames-usage": {
    "scope": "javascript",
    "prefix": ["classnames usage"],
    "body": ["${1:classNames}('${2:foo}', '${3:bar}');"]
  },
```
So basically if you think some of them without modifications could be used in Typescript, we can add just typescript as the value inside ``scope``. 
https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-scope

**Comment by covertbert** [comment]
@lnikell All JS is valid TS so there's no reason not to just enable it for `.ts` and `.tsx` files too IMO

**Comment by lnikell** [comment]
@covertbert @deadcoder0904 @BjoernRave I've added a typescript scope for all available snippets. As per our discussion the best thing we can do at this moment to enable all current snippets for Typescript too, and if there is someone who could adjust and create Typescript specific versions please feel free to contribute.

For typescript, there are two scopes that could be set for the snippet `typescript,typescriptreact`. `typescript` will work only in `*.ts` files and `typescriptreact` will work in `*.tsx`.

Example of the Typescript compatible snippet:

```
  "classnames-usage": {
    "scope": "javascript,javascriptreact,typescript,typescriptreact",
    "prefix": ["classnames usage"],
    "body": ["${1:classNames}('${2:foo}', '${3:bar}');"]
  },
``` 
For those who already installed extension to get the latest snippets you could reopen the project folder or manually trigger fetch with command palette - "Snipsnap - Fetch the snippets".

**Comment by covertbert** [comment]
Awesome, cheers guys! I’ll let you know how I get on using it with TypeScript and will contribute to fixing things where necessary!
