### ISSUE TITLE
Support for monorepo projects

### ISSUE THREAD

**Issue by masa-iwasaki** [snipsnapdev/snipsnap#32]
I tried Snipsnap with my hobby projects and found that Snipsnap didn't work as expected with monorepo projects.

Do you have any plan to support monorepo projects ?

**Comment by lnikell** [comment]
Hi @masa-iwasaki, actually it should work with monorepo too if it's structured as a workspace in VS Code. But in case if there are just multiple package.json files here and there it won't work as you mentioned since we only scan root folder. But it's a good point for considering for the next updates. We will think about how can we handle it.
