### ISSUE TITLE
I can't see the rest of the snippet

### ISSUE THREAD

**Issue by CaiqueR** [snipsnapdev/snipsnap#40]
In my VS Code I can't see the rest of the code snippet
![image](https://user-images.githubusercontent.com/42003129/85294586-33b69b00-b475-11ea-9950-89919a5c8442.png)

**Comment by lnikell** [comment]
Hi, @CaiqueR could you elaborate more on this?

Do you have some libraries that present in the list https://github.com/snipsnapdev/snipsnap/tree/master/snippets/javascript that you can't see?

Do you use yarn or npm?

**Comment by CaiqueR** [comment]
> Hi, @CaiqueR could you elaborate more on this?
> 
> Do you have some libraries that present in the list https://github.com/snipsnapdev/snipsnap/tree/master/snippets/javascript that you can't see?
> 
> Do you use yarn or npm?

Sorry, I expressed it wrong, I wanted to say that I can only see for example: "react compon ..." I don't know what is written ahead.

**Comment by Fasani** [comment]
I actually just installed it and I felt the same. 

Can we style the 'suggest box' to be wider?

**Comment by lnikell** [comment]
@Fasani no, I don't like it too because it requires to look on the right side inside the description part, rather than just have left side for navigation.
![image](https://user-images.githubusercontent.com/2697570/85304684-5021fa00-b4ac-11ea-9f51-64b50fc2e841.png)
VS Code does not allow I guess to customize the width of dropdown, but we will take a look.

**Comment by CaiqueR** [comment]
Hmm, ok. Thank you!

**Comment by gopalagrawal** [comment]
I raised the same question a few minutes back (before I read this one).   Just wanted to upvote this issue.  I think many people would like to get rid of the description in the left pane (2nd column) as it blocks of the short title in the 1st column.  You may delete my question if you need to since this issue has already been raised  (I seem unable to find the issue I raised and hence ... can't delete it myself).

**Comment by lnikell** [comment]
@gopalagrawal @CaiqueR I propose for everyone who has this issue too upvote that issue I raised in VS Code Github
https://github.com/microsoft/vscode/issues/100832 . Also there is an example of how it looked like before their latest updates.

**Comment by Fasani** [comment]
They shut your issue down because it already exists since 2017.

Semi-related to:
https://github.com/microsoft/vscode/issues/98228 - Open since 20 May 2020
https://github.com/microsoft/vscode/issues/29757 - Open since 28 Jun 2017
https://github.com/microsoft/vscode/issues/29126 - Open since 20 Jun 2017

The following hack was provided by @povilasbaranovas and you could *request* your userbase to do this *hack* or perhaps you can do it some how in a more intelligent way?

```
This is not a proper solution, but a hack that might break after any program update!

As VsCode is styled mainly using CSS to change the size you have to simply override default values.
This can be accomplished by using "Custom CSS and JS loader" extension and injecting your own CSS.

Width value is static 430px:
.monaco-editor .suggest-widget { width: 430px; }

Height value is set inline on element by editor depending on how many suggestions there are so !important is necessary to owerride it:
.monaco-editor .suggest-widget>.tree { height: 300px !important; }
```
