### ISSUE TITLE
How to prevent creation of snipsnap.code-snippets file in project's folder

### ISSUE THREAD

**Issue by heytulsiprasad** [snipsnapdev/snipsnap#47]
# Describe the problem

I've installed **snipsnap** from vscode marketplace and the extension is enabled globally. However up on opening any new project this folder called `.vscode` gets automatically created with a file name `snipsnap.code-snippets`. Is this a feature? I have been using other snippets extensions in the past which are enabled globally but doesn't create this type of folders or anything. **Why is this file needed?**

## Screenshots
This is what says upon opening up any new project in vs code:
![image](https://user-images.githubusercontent.com/52394293/85805657-8ab8ba80-b76a-11ea-9523-11224b8c3dc2.png)

## Fix wanted?

Is there a way to stop this from hapenning? Or shall we always need to add this to `.gitignore` which will be very repetitive to do?

**Comment by lnikell** [comment]
Hi @heytulsiprasad 
Thank you for the feedback. Currently, the behavior you described is correct, that how Snipsnap works. 

`snipsnap.code-snippets` contains all snippets that were fetched and relate to your current project. By VS Code standard any files that will be inside .vscode folder with `.code-snippets` extension will be automatically parsed and become part of the autocomplete. 

Other snippets extensions don't provide you snippets based on libraries you use, so they don't need to have any logic inside the extension and could just have json file with snippets that will be fetched once by VS Code. Snipsnap has logic, and as described in documentation we scan your package.json and lock files and request from the server only relevant to your project snippets. Another thing that other snippets are global, Snipsnap not. If we even add fetched snippets to the global vscode system folder, they will become visible for all your projects.

It's up to you to decide whether you want to put it to .gitignore or keep inside the project and share it with teammates. Because if you add it to your repository, snippets will become automatically available even for team members who have not installed the extension. 

Please upvote this issue if you want us to consider it as a priority.

Suggested workaround:
- we can automatically put `snipsnap.code-snippets` to .gitignore
- research ways of isolating snippets per project but having them installed in global vs code directory.

**Comment by heytulsiprasad** [comment]
I understand this entirely. It's a good feature of making the snippets available to all the people on the team rather than just those with extension and that too based on the packages that we use, which keep our setup lean. 

Although it depends entirely on the team whether or not they should acquire this feature, I think it's better to ask the user once they create a new workspace/project, whether or not they want to have it made public or just for them to access (then automatically add it to `.gitignore` file). 

However, this is still a suggestion, you should do what everybody feels like right. Thanks for your time, feel free to close this issue.

**Comment by lnikell** [comment]
Thank you @heytulsiprasad. Let's keep this issue opened for the time being to let others see it and leave their feedback too.

**Comment by vdeantoni** [comment]
I'm also interested in this.

Is there some kind of temporary storage that the extension could use to store the file without messing with the project files? And still provide the snippets?

Ideally, this behaviour would be behind a settings for the users to toggle.
